# ==============================================================================
# Run temp sensor design
# ==============================================================================

sky130hd_temp:
	python tools/temp-sense-gen.py --specfile test.json --output ./work --platform sky130hd --mode macro --clean


