import warnings
import sys
import os

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from common.get_ngspice_version import check_ngspice_version
            
def classify_sim_error(template_file, result_file, _generator_is) -> str:
    """Used to propogate out how close the generated simulations results are 
    from the results in the stored template files

    Args:
    - 'template_file' (string): The stored template file
    - 'result_file' (string): The result file generated by the simulations
    - '_generator_is' (dict): Contains info about the generator for which the simulation check is being run

    Returns:
    - str: The kind of alert
        - 'red' alert for very large difference in generated and template results
        - 'amber' alert if the difference lies within the allowable range
        - 'green' if ok
    """
    if _generator_is['sky130hd_temp']:
        sys.path.append(os.path.join(os.path.dirname(__file__), '../temp-sense-gen'))
        
    elif _generator_is['sky130hvl_ldo']:
        sys.path.append(os.path.join(os.path.dirname(__file__), '../ldo-gen'))
        
    elif _generator_is['sky130XX_cryo']:
        sys.path.append(os.path.join(os.path.dirname(__file__), '../cryo-gen'))
        
    from tools.compare_files import compare_files 
   
    ngspice_check_flag = check_ngspice_version()
    alerts = { 0: 'green', 1: 'amber', 2: 'red' }
    
    
    if ngspice_check_flag:
        if compare_files(template_file, result_file) == 0:
            return alerts[0]
        elif compare_files(template_file, result_file) == 1:
            warnings.warn('Simulation results do not match, but ngspice version matches!')
            return alerts[1]
        else:
            return alerts[2]
        
    elif ngspice_check_flag == 0:
        warnings.warn('NGSPICE version does not match!')
        if compare_files(template_file, result_file) == 0:
            return alerts[0]
        elif compare_files(template_file, result_file) == 1:
            warnings.warn('Simulation results do not match!')
            return alerts[1]
        else:
            return alerts[2]
