mimcap_m3:
	python3 mimcap_gen.py --input_file sky130_fd_pr__cap_mim_m3_1_FJK8MM.gds --pitch 2.48 --wtop 0.3 --wbot 0.3 --lyrtop 71

mimcap_m4:
	python3 mimcap_gen.py --input_file sky130_fd_pr__cap_mim_m3_2_FJK8MM.gds --pitch 4 --wtop 1.6 --wbot 0.3 --lyrtop 72
