name: sky130hvl_ldo-generator

on:
  push:
    branches:
    - main
  pull_request:
    paths:
      - 'openfasoc/common/**'
      - 'openfasoc/generators/common/**'
      - 'openfasoc/generators/ldo-gen/**'
  workflow_dispatch:

jobs:
  sky130hd_ldoGen:
    strategy:
      matrix:
        arrSize: ['', 50, 100, 150]
    runs-on: ubuntu-latest
    steps:
      - name: Remove unnecessary files
        run: |
          du . -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          du . -h

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test sky130hvl LDO
        env:
                IMAGE_NAME: msaligane/openfasoc:stable
                arrSize: ${{ matrix.arrSize }}
        run: |
          cd $GITHUB_WORKSPACE
          touch file.log
          docker run --rm \
            -v $PWD:$PWD\
            -w $PWD\
            $IMAGE_NAME\
            bash -c "\
              cp ./.github/scripts/parse_rpt.py ./openfasoc/generators/ldo-gen/. &&\
              pip3 install -r requirements.txt &&\
              cd ./openfasoc/generators/ldo-gen &&\
              arrSize=$arrSize make sky130hvl_ldo &&\
              python3 parse_rpt.py sky130hvl_ldo
            " && exit_code=$? | tee -a file.log
            if [ $? -ne 0 ]; then exit 1; fi
            if grep "\[ERROR\]" file.log; then exit 1; else exit 0; fi
